# Solving Sudoku

The primary description of this coursework is available on the CM20252 Moodle page. This is the Jupyter notebook you must complete and submit to receive marks. 

** You must follow all instructions given in this notebook. **

Restart the kernel and run all cells before submitting the notebook. This will guarantee that we will be able to run your code for testing.

Remember to save your work regularly. 

## Getting Started

You already know that you will be writing a Sudoku solver. You need to implement your solver in Python in this notebook. You can use any of the appropriate problem-solving techniques discussed in the lectures. You are encouraged to modify the basic algorithms. Be creative. 

You will be given Sudoku puzzles that either have a single solution or no solution. You will need to identify the solution, if there is one.

Below is a sample puzzle along with its solution. 

<img src="resources/images/Sudoku_unsolved.png" style="width: 200px;"/>
<img src="resources/images/Sudoku_solved.png" style="width: 200px;"/>


## Sample Sudokus

You can test your code on a set of 100 sample Sudoku puzzles. This set is similar to the test set that will be used to assess your work. 

The following code will load 100 Sudoku puzzles and their solutions into two `100x9x9` numpy arrays. Empty cells are designated by zeros. 

In [99]:
import numpy as np

# Load sudokus
sudokus = np.load("resources/data/sudokus.npy")
print("Shape of sudokus array:", sudokus.shape, "; Type of array values:", sudokus.dtype)

# Load solutions
solutions = np.load("resources/data/solutions.npy")
print("Shape of solutions array:", solutions.shape, "; Type of array values:", solutions.dtype, "\n")

# Print the first sudoku...
print("Sudoku #1:")
print(sudokus[0], "\n")

# ...and its solution
print("Solution of Sudoku #1:")
print(solutions[0])

Shape of sudokus array: (100, 9, 9) ; Type of array values: int32
Shape of solutions array: (100, 9, 9) ; Type of array values: int32 

Sudoku #1:
[[0 0 4 3 0 0 2 0 9]
 [0 0 5 0 0 9 0 0 1]
 [0 7 0 0 6 0 0 4 3]
 [0 0 6 0 0 2 0 8 7]
 [1 9 0 0 0 7 4 0 0]
 [0 5 0 0 8 3 0 0 0]
 [6 0 0 0 0 0 1 0 5]
 [0 0 3 5 0 8 6 9 0]
 [0 4 2 9 1 0 3 0 0]] 

Solution of Sudoku #1:
[[8 6 4 3 7 1 2 5 9]
 [3 2 5 8 4 9 7 6 1]
 [9 7 1 2 6 5 8 4 3]
 [4 3 6 1 9 2 5 8 7]
 [1 9 8 6 5 7 4 3 2]
 [2 5 7 4 8 3 9 1 6]
 [6 8 9 7 3 4 1 2 5]
 [7 1 3 5 2 8 6 9 4]
 [5 4 2 9 1 6 3 7 8]]


## Your code ##

Define a function called `sudoku_solver()` that takes **one** Sudoku puzzle (a $9 \times 9$ numpy array) as input and returns the solved Sudoku as a $9 \times 9$ numpy array. Note that the test set may contain invalid Sudokus, that is, Sudokus with no solution. In such a case, your function should return a $9 \times 9$ numpy array whose values are all equal to `-1`.  

You may use more than one cell to write your code (but this is not necessary).

In [100]:
"""
    Solves a Sudoku puzzle and returns its unique solution.

    Input
        sudoku : 9x9 numpy array of integers
            Empty cells are designated by 0.

    Output
        9x9 numpy array of integers
            It contains the solution, if there is one. If there is no solution, all array entries should be -1.

"""

def sudoku_solver(sudoku):
  
    ### YOUR CODE HERE
    
    start_puzzle = sudoku
    
    puzzle = get_puzzle(start_puzzle)
    
    solve(puzzle)
    
    if not solve(puzzle):
        invalid(puzzle)
    
    puzzle = np.array(puzzle);
    
    return puzzle


def check_cell(puzzle, col, row, value):
    if (check_row (puzzle, row, value)):
        if (check_col(puzzle, col, value)):
            if (check_box(puzzle, col, row, value)):
                return True
                #check_cell(puzzle, col, row)
    return False


def check_col(puzzle, col, value):

    for row in range (0,9):
        if puzzle[col][row] == value:
            return False
    return True

def check_row(puzzle, row, value): 
    for col in range (0,9):
        if puzzle[col][row] == value:
             return False
    return True

def check_box(puzzle, i, j, value):
    tlX, tlY = 3 *(i//3), 3 *(j//3)
    for x in range(tlX, tlX+3):
            for y in range(tlY, tlY+3):
                    if puzzle[x][y] == value:
                        return False             
    return True


def solve(grid, i=0, j=0):
    poss_nums = [0,1,2,3,4,5,6,7,8,9]
    i,j = find_cell(grid, i, j)
    if i not in poss_nums:
        #print("board solved")
        grid = np.array(grid)
        return True
    for e in range(1,10):
            if check_cell(grid,i,j,e):
                    grid[i][j] = e
                    if solve(grid, i, j):
                            return True
                    grid[i][j] = 0

    return False

def get_puzzle(start_puzzle):
    n = 9
    puzzle = [[0 for i in range(n)] for j in range(n)]  
    for col in range (0,9):
        for row in range (0,9):  
            puzzle[col][row] = start_puzzle[col][row]
    return puzzle

def find_cell(grid, i, j):
    for x in range(0,9):
        for y in range(0,9):
            if grid[x][y] == 0:
                return x,y
    return 10,10

def invalid(puzzle):
    for x in range (0,9):
        for y in range (0,9):
            puzzle[x][y] = -1;
            
def unsolved(puzzle):
    for x in range(0,9):
        for y in range(0,9):
            if (puzzle[x][y] == 0):
                return True
    return False


## Testing your code

You can test your code on the sudoku puzzles that we have provided. For example, the following code cell should return `True` if your `sudoku_solver()` function can correctly solve the first sudoku. This will work only if all of your code is above the test cell. Otherwise, the test cell does not have access to the `sudoku_solver()` function.

In [101]:

for y in range (0,100):
    print(np.array_equal(sudoku_solver(sudokus[y]), solutions[y]))


True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


## How we will test your code

We will test your code using the hidden tests in the following cell. Specifically, the hidden tests will test your `sudoku_solver()` function on a different set of 100 sudoku puzzles of similar difficulty. **Make sure all of your code is above our test cell. ** Otherwise, the test cell will not have access to the sudoku_solver() function and you will receive zero marks.

In [18]:
# This is the TEST CELL. Do not delete or change. All of your code must be written above this cell. 